### ISSUE TITLE
Can we use RGB-D images from mobile phones with Depth Sensor Camera?

### ISSUE THREAD

**Issue by Fizmath** [SimingYan/Hybrid_Relative_Pose#3]
Hello

Before cloning the repo and running the code I have a question. I am rather confused about the input images.

What exactly  input images should be ?

Can we use a few plain RGB-D image from a  mobile phone with  Depth Sensor Camera ?
I want to build a complete 3D perimeter of a room by just taking a few separate photos with overlapping areas  from all sides of the room. Is it possible with your method ?

Thank you for the code

**Comment by SimingYan** [comment]
Hi,

The input image should be RGB-D. Sorry for the misunderstanding here. If you have a training dataset, I think our method can help you register the photos you take. If not, I'm not sure whether our pre-trained model on the scannet have the good transfer ability to get accurate registration of your room, but you can have a try!

**Comment by Fizmath** [comment]
Thank you very much for the reply

At long last I installed and ran your code, got many errors. Anyway, now I captured four RGB photos from 4 sides of my room with good overlapping between the photos  then I extracted their depth image, would you please give some hints how to feed these images to your code to get the complete perimeter of the room  and visualize the results  ? 

Which files from your repo should I use ?
